@echo off
echo Starting Test Data Editor...

echo Starting Backend API...
start cmd /c "cd tools\test-data-editor && node server.js"

echo Starting Frontend UI...
cd tools\test-data-editor\frontend
start cmd /c "npm run dev"

echo Waiting for UI to compile...
timeout /t 3 /nobreak >nul

echo Opening browser...
start http://localhost:5173
